sitename: Cloud Demo
author: Cardy
primary_color: 200
cover: /cover.webp
logo: /favicon.svg
quote_card_content: 希望你今后的每一次笑，都是真心的。
quote_card_source: '-- 南河「深海」'
iconfont_url: //at.alicdn.com/t/c/font_4667994_9xxq6pvagei.css
page_size: 6
menu:
  - name: 首页
    url: /
  - name: 归档
    url: /archives
  - name: 标签
    url: /tags
  - name: 收藏
    url: /collections
  - name: 关于
    url: /about
avatar: /cover.webp
description: 一个简单的博客
social:
  - name: github
    url: https://github.com/DuranceX
  - name: zhihu
    url: https://www.zhihu.com/
  - name: weibo
    url: https://www.weibo.com/
  - name: twitch
    url: https://www.twitch.com/
collections:
  - name: GitHub仓库
    url: https://github.com/DuranceX/Astro-Cloud
    favicon: /favicon.svg
    desc: Cloud主题GitHub仓库
  - name: Placeholder
    url: /
    favicon: https://img95.699pic.com/photo/60017/2391.jpg_wh860.jpg
    desc: 这是一个长长长长长长长长长长长长长长长长长长长长的描述
  - name: Placeholder234
    url: /
    favicon: https://img95.699pic.com/photo/60017/2391.jpg_wh860.jpg
    desc: 这是一个长长长长长长长长长长长长长长长长长长长长的描述
  - name: Placeholder345
    url: /
    favicon: https://img95.699pic.com/photo/60017/2391.jpg_wh860.jpg
    desc: 这是一个长长长长长长长长长长长长长长长长长长长长的描述
  - name: Placeholder
    url: /
    favicon: https://img95.699pic.com/photo/60017/2391.jpg_wh860.jpg
    desc: 这是一个长长长长长长长长长长长长长长长长长长长长的描述
  - name: Placeholder
    url: /
    favicon: https://img95.699pic.com/photo/60017/2391.jpg_wh860.jpg
    desc: 这是一个长长长长长长长长长长长长长长长长长长长长的描述
